# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

#COMMENT OUT THIS ONE IF YOU WANNA WORK ON SHIT
development:
  host: 198.199.68.202
  adapter: postgresql
  encoding: utf8
  database: katibean
  pool: 5
  username: root
  password: foobar

#UNCOMMENT THIS IF YOU WANNA WORK ON SHIT
#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: katibeen_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: katibeen_production
  pool: 5
  username:
  password:
